name: browser_detect
version: 1.0.4+1
author: Dan Schultz <dan@mixbook.com>
description: A library that provides information about the user`s web browser.
homepage: http://www.github.com/danschultz/browser_detect.dart
environment:
  sdk: '>=2.0.0-dev.52.0 <2.0.0'

dependencies:

dev_dependencies:
  build_runner: ^0.8.8
  build_web_compilers: ^0.4.0
  build_test: ^0.10.2
  unittest: any
